### Create a new highscore
POST http://localhost:8000/highscore
Accept: application/json

{
  "name": "HUHU",
  "score": 9999
}

### Get all highscores
GET http://localhost:8000/highscore?page=0&page_size=5